name: Deploy to Render

# 📦 Esto indica cuándo se dispara el workflow
on:
  push:
    branches: [master]  # Reemplazá "main" si usás otra rama principal (como "master" o "production")

jobs:
  deploy:
    runs-on: ubuntu-latest  # Sistema operativo usado por GitHub Actions

    steps:
      - name: Llamar al Webhook de Render
        run: curl -X POST "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
